// ==UserScript==
// @name YouTubeRemoveShorts
// @namespace yt
// @version 1.3
// @match https://www.youtube.com/*
// @grant none
// @run-at document-idle
// ==/UserScript==
(function(){'use strict';const R='https://www.youtube.com/';function x(e){if(!e)return;try{e.style.setProperty('display','none','important');e.remove&&e.remove();}catch(_){}}function p(r=document){r.querySelectorAll('a[href*="/shorts/"],ytd-rich-item-renderer a[href*="/shorts/"]').forEach(a=>x(a.closest('ytd-rich-item-renderer')||a));r.querySelectorAll('ytd-rich-shelf-renderer,ytd-shelf-renderer,ytd-rich-grid-row,ytd-reel-shelf-renderer').forEach(s=>{if((s.textContent||'').toLowerCase().includes('shorts'))x(s)});r.querySelectorAll('yt-formatted-string.style-scope.ytd-video-meta-block,span#badge,span.ytd-thumbnail-overlay-time-status-renderer,ytd-badge-supported-renderer').forEach(b=>{if((b.textContent||'').toLowerCase().includes('shorts')||((b.getAttribute&&b.getAttribute('aria-label')||'').toLowerCase().includes('shorts'))){x(b.closest('ytd-video-renderer')||b.closest('ytd-grid-video-renderer')||b.closest('ytd-rich-item-renderer')||b)}});r.querySelectorAll('ytd-compact-video-renderer,ytd-compact-autoplay-renderer,ytd-compact-playlist-renderer').forEach(s=>{if((s.textContent||'').toLowerCase().includes('shorts'))x(s)});r.querySelectorAll('a[title*="Shorts"],a[href*="/shorts/"]').forEach(a=>x(a));r.querySelectorAll('tp-yt-paper-tab').forEach(t=>{if((t.textContent||'').toLowerCase().includes('short'))x(t)});}document.addEventListener('click',e=>{const a=e.target.closest&&e.target.closest('a[href]');if(a&&a.href&&a.href.includes('/shorts/')){e.preventDefault();window.location.href=R}},true);const o=new MutationObserver(m=>{m.forEach(n=>{n.addedNodes&&n.addedNodes.forEach(k=>{k.nodeType===1&&p(k)})});p(document)});o.observe(document.documentElement||document.body,{childList:true,subtree:true});p(document);function c(){try{if(location.pathname&&location.pathname.toLowerCase().includes('/shorts/')){if(location.href!==R)window.location.replace(R)}}catch(_){}}(function(h){const P=h.pushState;h.pushState=function(){P.apply(h,arguments);setTimeout(c,100)};const R2=h.replaceState;h.replaceState=function(){R2.apply(h,arguments);setTimeout(c,100)}})(window.history);c();setInterval(p,3000);})();
